# Generated by Django 5.0.3 on 2024-05-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='adhar_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='pan_card',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='minimum_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
