# Generated by Django 5.0.3 on 2024-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
